Repository santibatte/dpa_2021, pull requests merged in 2021-04, with the labels that each got.

#76 Issue 74
  _robdir/rob_sandbox2.ipynb
  dpa_main.py
  results/metadata/.gitkeep
  src/etl/ingesta_almacenamiento.py
  src/etl/transformation.py
  src/pipeline/feature_engineering.py
  src/utils/params_gen.py
Labels: enhancement

#87 deletes double pickling
  src/etl/ingesta_almacenamiento.py
Labels: bug

#86 Issue 80
  _robdir/rob_sandbox.ipynb
  _robdir/rob_sandbox2.ipynb
  src/etl/ingesta_almacenamiento.py
  src/etl/transformation.py
  src/pipeline/luigi/feature_engineering.py
  src/pipeline/luigi/luigi_tmp_files/extract_metadata.csv
  src/pipeline/luigi/luigi_tmp_files/transformation_metadata.csv
  src/utils/params_gen.py
  src/utils/utils.py
Labels: enhancement

#95 Issue 80
  _robdir/rob_sandbox.ipynb
  src/etl/ingesta_almacenamiento.py
  src/pipeline/feature_engineering.py
  src/pipeline/luigi/extract.py
  src/pipeline/luigi/extract_metadata.py
  src/pipeline/luigi/feature_engineering_metadata.py
  src/pipeline/luigi/save_s3.py
  src/pipeline/luigi/saves3_metadata.py
  src/pipeline/luigi/transform.py
  src/utils/params_gen.py
Labels: bug

#109 Issue 88
  src/etl/transformation.py
  src/pipeline/luigi/a_extract.py
  src/pipeline/luigi/b_extract_test.py
  src/pipeline/luigi/c_extract_metadata.py
  src/pipeline/luigi/copy_table_example.py
  src/pipeline/luigi/d_save_s3.py
  src/pipeline/luigi/e_saves3_test.py
  src/pipeline/luigi/f_saves3_metadata.py
  src/pipeline/luigi/g_transform.py
  src/pipeline/luigi/h_transform_test.py
  src/pipeline/luigi/i_transform_metadata.py
  src/pipeline/luigi/j_feature_engineering.py
  src/pipeline/luigi/k_feature_engineering_test.py
  src/pipeline/luigi/l_feature_engineering_metadata.py
  src/pipeline/luigi/luigi_tmp_files/extract_unittest.csv
  src/pipeline/luigi/luigi_tmp_files/feature_engineering_unittest.csv
  src/pipeline/luigi/luigi_tmp_files/model_selection_metadata.csv
  src/pipeline/luigi/luigi_tmp_files/model_selection_unittest.csv
  src/pipeline/luigi/luigi_tmp_files/model_training_metadata.csv
  src/pipeline/luigi/luigi_tmp_files/model_training_unittest.csv
  src/pipeline/luigi/luigi_tmp_files/saveS3_unittest.csv
  src/pipeline/luigi/luigi_tmp_files/tansform_unittest.csv
  src/pipeline/luigi/m_model_training.py
  src/pipeline/luigi/n_model_training_test.py
  src/pipeline/luigi/o_model_training_metadata.py
  src/pipeline/luigi/p_model_selection.py
  src/pipeline/luigi/q_model_selection_test.py
  src/pipeline/luigi/r_model_selection_metadata.py
Labels: enhancement

#111 Issue 103
  _robdir/rob_sandbox.ipynb
  src/pipeline/feature_engineering.py
  src/pipeline/luigi/j_feature_engineering.py
  src/pipeline/luigi/m_model_training.py
  src/pipeline/model_selection.py
  src/pipeline/models_training.py
  src/utils/params_gen.py
Labels: enhancement

#114 Issue 107
  _robdir/rob_sandbox.ipynb
  src/pipeline/feature_engineering.py
  src/pipeline/luigi/j_feature_engineering.py
  src/pipeline/luigi/m_model_training.py
  src/pipeline/luigi/o_model_training_metadata.py
  src/pipeline/luigi/p_model_selection.py
  src/pipeline/luigi/r_model_selection_metadata.py
  src/pipeline/model_selection.py
  src/pipeline/models_training.py
  src/utils/params_gen.py
Labels: enhancement

#122 Issue 104
  src/etl/ingesta_almacenamiento.py
  src/pipeline/luigi/a_extract.py
  src/pipeline/luigi/d_save_s3.py
  src/pipeline/models_training.py
Labels: bug

#125 updating latest requirements
  requirements.txt
Labels: documentation

#127 Issue 117
  _robdir/rob_sandbox.ipynb
  src/pipeline/feature_engineering.py
Labels: enhancement

#129 Ch5 beta
  README.md
  _robdir/rob_sandbox.ipynb
  images/DAG_checkpoint5.png
  requirements.txt
  sql/create_schema_and_tables.sql
  src/etl/ingesta_almacenamiento.py
  src/pipeline/feature_engineering.py
  src/pipeline/luigi/b_extract_test.py
  src/pipeline/luigi/e_saves3_test.py
  src/pipeline/luigi/extract.py
  src/pipeline/luigi/h_transform_test.py
  src/pipeline/luigi/k_feature_engineering_test.py
  src/pipeline/luigi/n_model_training_test.py
  src/pipeline/luigi/q_model_selection_test.py
  src/pipeline/luigi/save_s3.py
  src/pipeline/model_selection.py
  src/pipeline/models_training.py
Labels: enhancement
